apiVersion: skaffold/v2beta17
kind: Config
metadata:
  name: spr-boot-app
build:
  artifacts:
    - image: tzdanows/monorepo-sprboot
      context: .
      jib: {}
deploy:
  kubectl:
    manifests:
      - ./k8s/deploy.yaml
      - ./k8s/service.yaml